javac GaussianAlgorithm.java
jar cfve release.jar GaussianAlgorithm GaussianAlgorithm.class GaussianAlignmentBuilder.class GaussianSolvedItem.class GaussianSolvedItemList.class GaussianSystem.class GaussianSystemInput.class GaussianUtilities.class GaussianAlignment.class GaussianLine.class
java -jar release.jar
